In [1]:
import pandas as pd

df = pd.read_csv("2016.csv")

In [5]:
df.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,ReportDate,API_WELLNO,FileNo,Company,WellName,Quarter,Section,...,Wtr,Days,Runs,Gas,GasSold,Flared,Lat,Long,Online_Date,Days_Online
0,0,14709,51,2016-01-01,3.306101e+13,17795.0,"EOG RESOURCES, INC.",ROSS 3-04H,LOT3,4.0,...,572.0,13.0,625.0,644.0,524.0,0.0,48.371760,-102.520252,2016-01-01,0
1,1,14859,201,2016-01-01,3.306101e+13,16893.0,STATOIL OIL & GAS LP,BAKKE 23 1-H,NWNW,23.0,...,227.0,3.0,0.0,4.0,4.0,0.0,48.239382,-102.481139,2016-01-01,0
2,2,14876,218,2016-01-01,3.306101e+13,19058.0,STATOIL OIL & GAS LP,BURES 20-29 #1TFH,NWNE,20.0,...,4638.0,27.0,3731.0,2823.0,2540.0,283.0,48.239688,-102.665406,2016-01-01,0
3,3,14941,283,2016-01-01,3.306102e+13,22461.0,STATOIL OIL & GAS LP,LIFFRIG 29-20 #4H,SWSW,29.0,...,4704.0,13.0,4777.0,7554.0,7121.0,433.0,48.299268,-102.671472,2016-01-01,0
4,4,14947,289,2016-01-01,3.306102e+13,22007.0,STATOIL OIL & GAS LP,PANZER 22-23 #1-H,SWSW,22.0,...,2.0,1.0,386.0,6.0,6.0,0.0,48.228895,-102.502487,2016-01-01,0